### ISSUE TITLE
Make use of shader panel

### ISSUE THREAD

**Issue by BrunoBieri** [CodingEric/Erics-MagicaVoxel-Shaders#5]
As stated in the release notes of MagicaVoxel 0.99.5.1 - 6/5/2020 (https://ephtracy.github.io/)

`Voxel Shader panel
- Can bind user defined arguments to the interface via comments. `

It would be nice to see the shaders make use of this panel.

**Comment by tyanyuy3125** [comment]
I apologize for a delayed comment.

As to this issue, I have added it to my development roadmap with a high priority.

Nevertheless, as you may have noticed, due to some personal affairs, perhaps I could not get the work done in at least 4 months. Since you seem to be able to modify the shaders, your PRs are also welcomed.

**Comment by tyanyuy3125** [comment]
Done in Version 54.
